### ISSUE TITLE
Missing windowbordertiles.bin

### ISSUE THREAD

**Issue by Matthamatic** [ShiningForceCentral/SF2DISASM#29]
the split list seems to be missing the entry for windowbordertiles.bin. I was unable to build without the file. I added the entry back and everything seems good now.

#split	0x1264E,0x126EE,data/graphics/tech/windowborder/windowbordertiles.bin

**Comment by xenometal** [comment]
The file `data/graphics/tech/windowborder/windowbordertiles.bin` is not included anymore because it was the result of a misunderstanding; the data is in fact the layout for the portrait window and should be formatted to ASM.

This should be fixed as of commit 53f57d120ec20a7bf292626fb7603f89a87b7e07 where references to `data/graphics/tech/windowborder/windowbordertiles.bin` have been removed and `data/graphics/tech/windowlayouts/portraitwindowlayout.asm` has been updated.
